### ISSUE TITLE
Only part of the full url is highlighted

### ISSUE THREAD

**Issue by jdhao** [itchyny/vim-highlighturl#1]
My URL is like `http://192.168.10.1:1080/test/test_test`. Only the texts before the underline character `_`  are highlighted correctly. 

![image](https://user-images.githubusercontent.com/16662357/58612469-48157c00-82e5-11e9-884f-5d7f75a89f51.png)

Is this the expected behavior? Or my URL is not a valid URL?

**Comment by itchyny** [comment]
Thanks for reporting the issue. I fixed the problem by 5ab7d890c1a764277f2002f7dbe0b597df64a885. Please confirm.

**Comment by jdhao** [comment]
Thanks for your prompt reply. This issue has been fixed.
