### ISSUE TITLE
Request: highlight URLs without scheme

### ISSUE THREAD

**Issue by sfsam** [itchyny/vim-highlighturl#2]
It'd be nice to highlight URLs without the scheme. For example, [github.com](https://github.com) would be highlighted. To make implementation a little easier, maybe this could work for only the most popular TLDs like .com, .net, .org, etc. This highlighting behavior could be off by default, but enabled with a flag.

**Comment by itchyny** [comment]
I believe you can configure `g:highlighturl_pattern` to enable highlight for the pattern you want. I don't think I will use this and not motivated to maintain the TLD list in this plugin.
