### ISSUE TITLE
Multiple urls in the same line separated by comma are higlighted as one url.

### ISSUE THREAD

**Issue by jdhao** [itchyny/vim-highlighturl#3]
For example,  `"https://www.google.com,https://baidu.com"`, the two urls will be highlighted as one URL.

**Comment by itchyny** [comment]
Commas in URLs is allowed in general. Should we check the following word is not like a scheme?

**Comment by jdhao** [comment]
yes, it may be worth checking if the URL pattern to highlight has multiple schemas (for example, multiple `http://` ) and separate it properly. But that may not be easy to write in Vim script.

**Comment by itchyny** [comment]
But https://www.google.com/search?q=https://google.com is a valid one URL. Anyway, I have already fixes around this, and will push tonight.
