### ISSUE TITLE
Option to disable automatic highlight group creation

### ISSUE THREAD

**Issue by mehalter** [itchyny/vim-highlighturl#5]
I love this plugin and want to use it with various colorschemes that allow me to add highlight groups freely. Is there an option to disable the autocommand in the setup for setting the highlight group and just rely on the `HighlightURL` group to be defined? It could be just a `g:highlighturl_skip_highlight` or something that would just make it to where the `augroup` justt runs the `set_url_match` function.

**Comment by itchyny** [comment]
I added `default` attribute not to overwrite. Please check if it resolves the issue.
