### ISSUE TITLE
Toggle and Disable functions not working

### ISSUE THREAD

**Issue by mehalter** [itchyny/vim-highlighturl#6]
Could you explain how the toggle and disable functions work? I can't seem to get either to work and it would be nice to enable and disable the url highlighting during runtime. I am trying to run `:call highlighturl#toggle()` and nothing is changing.

**Comment by itchyny** [comment]
This is how it works.
![](https://user-images.githubusercontent.com/375258/165655957-3e29f0f2-f8ee-4062-928f-ee5ec7b63627.gif)

**Comment by mehalter** [comment]
Hm I'm not getting this functionality working sadly. I'll have to look into it in the coming days

**Comment by mehalter** [comment]
This is coming from Neovim renaming the match group to `HighlightURL` instead of what is specified in the plugin `HighlightUrl`. I am going to close this since it seems to be not related to the functionality of the plugin and should be fixed upstream in Neovim.
